### ISSUE TITLE
追加のテーブル作成と、入力フォームの作成

### ISSUE THREAD

**Issue by jdmaoe** [Group2-HALcinema/Group2#142]
映画テーブルの変更、カテゴリテーブルの追加、映画テーブルとカテゴリテーブルへの入力フォームを作成する。

**追記**
料金テーブル、割引テーブル、上映テーブル、映画テーブル、時間テーブルにデータを入力できるフォームを作る。
上映テーブルに関しては、足りていない項目の入力フォームを追加する。
映画テーブルは、上映時間の入力フォームを追加する。

期限：7/19日（夏休み期間前）まで

**Comment by hsyzk** [comment]
pupu
