### ISSUE TITLE
マイページにフォームを作成とその他作業

### ISSUE THREAD

**Issue by jdmaoe** [Group2-HALcinema/Group2#148]
・チケット購入時に必要な、addressテーブルの個人情報を入力するフォームを作る。
・割引テーブルに登録する割引の内容を考える。
・料金テーブルに登録する情報を考える。
・上映テーブルに登録する映画を選ぶ。（上映中にいれる映画と公開予定に入れる映画に分ける。）
・映画テーブルの上映開始日と上映終了日を考える。（期間は7日間で考える）
・映画テーブルに上映時間の項目を追加するので、各映画の上映時間を調べる。
・新たに時間テーブルを作ります。そこに登録する情報を考える。開始時間を５つほど考えてほしい
　（終了時間は、開始時間に上映時間を足して表示する予定）

期限：7月19日（夏休み期間前）まで

**Comment by BASARA0826** [comment]
進捗ダメです。
プログラムの記述方法がわからんのは調べたら出てくるから多分大丈夫やけどどこに何が書いてあるのか現状全く把握できない。どの行の変数がどこに依存してるかが把握できんから下手に書き込めない

**Comment by jdmaoe** [comment]
auth.pyはログイン周りの機能と、管理者ページの入力フォームが書いてある。
views.pyは座席の予約機能が書いてある。Chatgptとかに関数のコードを渡して、「わかりやすく説明して」みたいに投げると説明してくれる。記述に関しては一番したに書き足す感じでいいよ。
調べもの系完了わかりました。
