### ISSUE TITLE
予約システム完成

### ISSUE THREAD

**Issue by jdmaoe** [Group2-HALcinema/Group2#162]
チケット購入までの流れ
映画の選択（トップページ、上映中一覧ページ）→上映の日付、時間帯の選択（映画詳細ページ）→
座席配置図から座席の選択（座席選択ページ）→選択された内容の確認、料金の表示、支払方法の選択（購入内容ページ）→
支払情報の入力（お客様情報ページ）→支払の確認→購入完了

**Comment by hsyzk** [comment]
できました
