### ISSUE TITLE
各ページのリンクの修正

### ISSUE THREAD

**Issue by jdmaoe** [Group2-HALcinema/Group2#94]
各ページのa、link、imgタグをFlask用の書き方に変更する。
例）a href="top.html"　→　a href="{{ url_for('index') }}"
　　link rel="stylesheet" href="../../static/css/reset.css"　→　link rel="stylesheet" href="{{url_for('static', filename='css/reset.css')}}"
　　img src="../../static/images/logo2.png"　→　img src="{{url_for('static', filename='images/logo2.png')}}"
　　
<>がついてない理由について、<>をつけるとコードとして判定をもらってしまい文字が読めなくなってしまうのでここでは、消して記述しています。実際にコードを修正するさいには、<>は消しませんのでお願いします。

aタグについて、 a href="{{ url_for('index') }}"  の   'index'  のところに対応したページの関数名を記述する
以下のような関数が記述してあるのは、viewsファイルの中にあるauth.pyとviews.pyです。

topページ例）
@app.route("/")
def index():　　　　　←　defの右が関数名　＊この場合index
    return render_template('top.html')　　　←　'top.html' が遷移先のページ

修正済みのページは、トップページ、公開予定一覧ページ、上映中一覧ページです。
上記の３ページを参考にするとやりやすいと思います。
わからないことがあったら聞いてください。

修正の確認は、VScodeのターミナルでflask runと入力して *Running on http://127.0.0.1:5000
のようなURLが表示されるのでそれを開くと確認できます。この際、エラーが出ると思いますが、そのエラーはバック側で使うモジュールがインポートされていないことにより発生するエラーなので、簡単に解決できます。エラー文をChatGPTなどに投げると、pip install 〇〇〇のように教えてくれるので、そのコードをVScodeのターミナルで実行してください。

**追記２**
バックエンドの都合により、関数が記述されているページが変わりました。これによりaタグの記述方法が変わります。

views.pyに移動した関数について、移動前は  a href="{{ url_for('movielist') }}"  と記述していたと思いますが
移動後は  a href="{{ url_for('views.movielist') }}"  のように、関数の前にviews. をつけないとうまく動作しません。
関数のまえにviews. をつけないといけない関数はviewsファイルの中にあるviews.pyに記述されていますが、確認するのが面倒な方用に、関数をリストアップしておきます。

関数の前にviews. をつけないといけない関数：cominglist、intoedit、moviedetail、movielist、screen、sitemap、ticketdetail

期限は、７月５日（金）までとします。

**Comment by motiko9673** [comment]
雅仁君は今やってるページと自分でやったページ
海翔君は自分でやったページとticketDetails.html
琉斗君は自分でやったページとsignup.htmlとsignin.html
をお願いいたします

**Comment by motiko9673** [comment]
追記ナビで遷移できる画面には背景画像を入れてください
    <div class="backimg"><img src="{{url_for('static', filename='images/eigakan2.jpg')}}" alt=""></div>
  これをナビとメインの間に入れてくれれば出ます。ピンとこない人はtop.htmlに書いてあるのでそれを参照してください
